# Generated by Django 4.1.13 on 2024-09-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0016_booking_status_alter_booking_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
