# Generated by Django 4.1.13 on 2024-09-19 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0016_booking_status_alter_booking_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('coachType', models.CharField(max_length=2)),
                ('numberOfSeats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('trainName', models.CharField(max_length=100)),
                ('trainNumber', models.CharField(max_length=10, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField(default='00:00')),
                ('travelDuration', models.CharField(max_length=10)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availableSeats', models.IntegerField()),
                ('trainType', models.CharField(max_length=50)),
                ('daysOfOperation', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='route',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobackend.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='djangobackend.train'),
        ),
        migrations.AddField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='djangobackend.train'),
        ),
    ]
