# Generated by Django 4.1.13 on 2024-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "djangobackend",
            "0017_delete_item_remove_tour_max_group_size_tour_seat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="personDetails",
            field=models.JSONField(default=list),
        ),
    ]
