# Generated by Django 4.1.13 on 2024-09-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0017_coach_route_station_train_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='max_group_size',
        ),
        migrations.AddField(
            model_name='tour',
            name='seat',
            field=models.JSONField(default=list),
        ),
    ]
